# indi-allsky caddy config
#
# Validate config
# caddy validate --config /etc/indi-allsky.Caddyfile
{
    #debug

    http_port %HTTP_PORT%
    https_port %HTTPS_PORT%

    ### ACME options
    #email admin@example.com
}

http:// {
    redir https://{host}:%HTTPS_PORT%{uri}
}

https:// {
    tls /etc/caddy/ssl/indi-allsky_caddy.pem /etc/caddy/ssl/indi-allsky_caddy.key

    ### Caddy generated certs (12 hour validity)
    #tls internal

    ### ACME
    #tls {
    #    on_demand
    #}

    log {
        output file /var/log/caddy/caddy.log
        format console
        level ERROR
    }

    redir / /indi-allsky/

    ### indi-allsky config
    handle /indi-allsky/images/* {
        root * %IMAGE_FOLDER%
        uri strip_prefix /indi-allsky/images
        file_server
    }

    handle /indi-allsky/static/* {
        root * %ALLSKY_DIRECTORY%/indi_allsky/flask/static
        uri strip_prefix /indi-allsky/static
        file_server
    }

    handle /indi-allsky/* {
        reverse_proxy %UPSTREAM_SERVER%
    }

    ### ADSB Aircraft tracking
    handle /skyaware/data/* {
        root * /run/dump1090-fa
        uri strip_prefix /skyaware/data
        file_server
    }

    handle /skyaware/data-978/* {
        root * /run/skyaware978
        uri strip_prefix /skyaware/data-978
        file_server
    }

    handle /skyaware* {
        root * /usr/share/skyaware/html
        uri strip_prefix /skyaware
        file_server
    }
}
