# indi-allsky caddy config
#
# Validate config
# caddy validate --config /etc/indi-allsky.Caddyfile
#
# Import config via the caddy API (the generated warning may be ignored)
# CADDY_JSON_TMP=$(mktemp --suffix=.json); echo "$CADDY_JSON_TMP"; caddy adapt --config /etc/indi-allsky.Caddyfile | jq > "$CADDY_JSON_TMP"; curl "http://localhost:2019/load" -H "Content-Type: application/json" -d @"$CADDY_JSON_TMP"; rm -f "$CADDY_JSON_TMP"

{
    http_port %HTTP_PORT%
    https_port %HTTPS_PORT%
}

http://, https:// {
    tls internal
    tls {
        on_demand
    }

    redir / /indi-allsky/

    ### indi-allsky config
    handle /indi-allsky* {
        handle /images/* {
            root * %IMAGE_FOLDER%
            file_server
        }

        handle /static/* {
            root * %ALLSKY_DIRECTORY%/indi_allsky/flask/static
            file_server
        }

        handle {
            reverse_proxy %UPSTREAM_SERVER%
        }
    }

    ### ADSB Aircraft tracking
    handle /skyaware* {
        handle /data/* {
            root * /run/dump1090-fa
            file_server
        }

        handle /data-978/* {
            root * /run/skyaware978
            file_server
        }

        handle {
            root * /usr/share/skyaware/html
            file_server
        }
    }
}
