FROM indi.base

ARG DEBIAN_FRONTEND=noninteractive

USER root
RUN apt-get update
RUN apt-get -y upgrade

RUN apt-get -y install \
    indi-full \
    libindi-dev \
    indi-webcam \
    indi-asi \
    libasi \
    indi-qhy \
    libqhy \
    indi-playerone \
    libplayerone \
    indi-svbony \
    libsvbony \
    libaltaircam \
    libmallincam \
    libmicam \
    libnncam \
    indi-toupbase \
    libtoupcam \
    indi-gphoto \
    indi-sx \
    indi-dsi \
    indi-gpsd \
    indi-gpsnmea


    # Unnecessary
    #gsc \


# cleanup
RUN apt-get clean


#RUN rm -f /etc/sudoers.d/allsky


COPY docker/start_indiserver.sh /home/allsky
RUN chown allsky:allsky /home/allsky/start_indiserver.sh
RUN chmod 755 /home/allsky/start_indiserver.sh


USER allsky
WORKDIR /home/allsky


ENTRYPOINT ["./start_indiserver.sh"]
