### INCOMPLETE ###

FROM docker_indi_base

ENV DEBIAN_FRONTEND noninteractive

USER root

RUN chmod u+s /bin/su

#USER allsky
#WORKDIR /home/allsky


CMD ["/usr/local/bin/indiserver", "-p 7624", "indi_simulator_telescope", $INDIALLSKY_CCD_DRIVER]
