### INCOMPLETE ###

FROM debian:bullseye-slim

ENV DEBIAN_FRONTEND noninteractive

USER root

RUN apt-get update && apt-get install -y \
    ca-certificates \
    nginx


COPY docker/start_nginx.sh /usr/local/sbin


CMD ["/usr/local/sbin/start_nginx.sh"]

