
FROM mariadb:jammy as mariadb_indi_allsky_pre

ENV DEBIAN_FRONTEND noninteractive

USER root
RUN apt-get update
RUN apt-get -y upgrade


# Final

FROM mariadb_indi_allsky_pre

ENV DEBIAN_FRONTEND noninteractive

USER root
RUN apt-get update
RUN apt-get -y upgrade


