
# docker- prefix due to files in docker/ folder
FROM docker-indi.base as indi.allsky.base

ARG DEBIAN_FRONTEND=noninteractive

USER root
RUN apt-get update
RUN apt-get -y upgrade


# minimum viable product packages
RUN apt-get -y install \
    build-essential \
    python3 \
    python3-dev \
    python3-venv \
    python3-pip \
    virtualenv \
    cmake \
    git \
    cpio \
    tzdata \
    ca-certificates \
    libgnutls28-dev \
    swig \
    libcurl4-gnutls-dev \
    libcfitsio-dev \
    libnova-dev \
    libdbus-1-dev \
    libglib2.0-dev \
    default-libmysqlclient-dev \
    pkg-config \
    ffmpeg \
    gifsicle \
    jq \
    libgpiod2 \
    i2c-tools \
    sqlite3


# optional packages in case python modules need to be compiled
RUN apt-get -y install \
    gfortran \
    libatlas-base-dev \
    libilmbase-dev \
    libopenexr-dev \
    libgtk-3-0 \
    libssl-dev \
    libxml2-dev \
    libxslt-dev \
    libffi-dev \
    libopencv-dev \
    libopenblas-dev \
    libraw-dev \
    libgeos-dev \
    libtiff5-dev \
    libjpeg62-turbo-dev \
    libopenjp2-7-dev \
    libpng-dev \
    zlib1g-dev \
    libfreetype6-dev \
    liblcms2-dev \
    libwebp-dev \
    libcap-dev \
    tcl8.6-dev \
    tk8.6-dev \
    python3-tk \
    libharfbuzz-dev \
    libfribidi-dev \
    libxcb1-dev \
    rustc \
    cargo


#RUN rm -f /etc/sudoers.d/allsky


RUN mkdir -m 750 /etc/indi-allsky
RUN chown -R allsky:allsky /etc/indi-allsky


RUN mkdir -p -m 755 /var/www/html/allsky
RUN chown -R allsky:allsky /var/www/html/allsky
VOLUME /var/www/html/indi-allsky


# cleanup
RUN apt-get clean


USER allsky
WORKDIR /home/allsky


RUN mkdir -m 755 /var/www/html/allsky/images
RUN mkdir -m 755 /var/www/html/allsky/images/darks
RUN mkdir -m 755 /var/www/html/allsky/images/export


COPY requirements/requirements_latest.txt /home/allsky
COPY requirements/requirements_optional.txt /home/allsky
COPY requirements/requirements_gpio.txt /home/allsky

RUN python3 -m venv /home/allsky/venv

ENV VIRTUAL_ENV=/home/allsky/venv
RUN /home/allsky/venv/bin/pip3 install --no-cache-dir --upgrade pip setuptools wheel
RUN /home/allsky/venv/bin/pip3 install --no-cache-dir -r requirements_latest.txt -r requirements_optional.txt -r requirements_gpio.txt
RUN /home/allsky/venv/bin/pip3 install --no-cache-dir "git+https://github.com/indilib/pyindi-client.git@674706f#egg=pyindi-client"

# cleanup
RUN rm -Rf /home/allsky/.cache/pip

