### INCOMPLETE ###

FROM indi_base

ENV DEBIAN_FRONTEND noninteractive

USER root
RUN apt-get update && apt-get -y upgrade


USER allsky
WORKDIR /home/allsky


CMD ["/usr/local/bin/indiserver", "-p 7624", "indi_simulator_telescope", $INDIALLSKY_CCD_DRIVER]
