
FROM docker_indi_allsky_base

ENV DEBIAN_FRONTEND noninteractive

USER root
RUN apt-get update
RUN apt-get -y upgrade


COPY docker/start_gunicorn.sh /home/allsky
RUN chown allsky:allsky /home/allsky/start_gunicorn.sh
RUN chmod 755 /home/allsky/start_gunicorn.sh



USER allsky
WORKDIR /home/allsky


ENTRYPOINT ["./start_gunicorn.sh"]
