local4.* -/var/log/indi-allsky/upgrade.log
& stop

local5.* -/var/log/indi-allsky/indiserver.log
& stop

local6.* -/var/log/indi-allsky/indi-allsky.log
& stop

local7.* -/var/log/indi-allsky/webapp-indi-allsky.log
& stop
