:%HTTP_PORT%, :%HTTPS_PORT% {
    tls internal
    tls {
        on_demand
    }

    redir / /indi-allsky/

    ### indi-allsky config
    handle /indi-allsky* {
        handle /images/* {
            root * %IMAGE_FOLDER%
            file_server
        }

        handle /static/* {
            root * /usr/share/indi-allsky/indi_allsky/flask/static
            file_server
        }

        handle {
            reverse_proxy unix//run/indi-allsky/gunicorn-indi-allsky.sock
        }
    }

    ### ADSB Aircraft tracking
    handle /skyaware* {
        handle /data/* {
            root * /run/dump1090-fa
            file_server
        }

        handle /data-978/* {
            root * /run/skyaware978
            file_server
        }

        handle {
            root * /usr/share/skyaware/html
            file_server
        }
    }
}
