# indi-allsky caddy config
#
# Validate config
# caddy validate --config /etc/indi-allsky.Caddyfile
{
    http_port %HTTP_PORT%
    https_port %HTTPS_PORT%
}

http:// {
    redir https://{host}:%HTTPS_PORT%{uri}
}

https:// {
    tls internal
    tls {
        on_demand
    }

    redir / /indi-allsky/

    ### indi-allsky config
    handle /indi-allsky* {
        handle /images/* {
            root * %IMAGE_FOLDER%
            file_server
        }

        handle /static/* {
            root * %ALLSKY_DIRECTORY%/indi_allsky/flask/static
            file_server
        }

        handle {
            reverse_proxy %UPSTREAM_SERVER%
        }
    }

    ### ADSB Aircraft tracking
    handle /skyaware* {
        handle /data/* {
            root * /run/dump1090-fa
            file_server
        }

        handle /data-978/* {
            root * /run/skyaware978
            file_server
        }

        handle {
            root * /usr/share/skyaware/html
            file_server
        }
    }
}
