### INCOMPLETE ###

FROM debian:bullseye-slim

ENV DEBIAN_FRONTEND noninteractive
ENV PYTHON_BIN=python3
ENV PYINDI_VERSION=git+https://github.com/indilib/pyindi-client.git@ce808b7#egg=pyindi-client


RUN apt-get update && apt-get install -y \
    lsb-release \
    sudo \
    build-essential \
    python3 \
    python3-dev \
    python3-venv \
    python3-pip \
    virtualenv \
    cmake \
    gfortran \
    whiptail \
    git \
    cpio \
    tzdata \
    ca-certificates \
    libgnutls28-dev \
    swig \
    libatlas-base-dev \
    libilmbase-dev \
    libopenexr-dev \
    libgtk-3-0 \
    libssl-dev \
    libxml2-dev \
    libxslt-dev \
    libgnutls28-dev \
    libcurl4-gnutls-dev \
    libcfitsio-dev \
    libnova-dev \
    libdbus-1-dev \
    libglib2.0-dev \
    libffi-dev \
    libopencv-dev \
    libopenblas-dev \
    pkg-config \
    rustc \
    cargo \
    ffmpeg \
    gifsicle \
    jq \
    sqlite3

    #rsyslog \
    #cron \
    #avahi-daemon \
    #policykit-1 \
    #dbus-user-session



ENV TZ=$INDIALLSKY_TIMEZONE
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


# need the uid and gid to match in all containers
RUN groupadd --gid 10001 allsky
RUN useradd --create-home --no-user-group --uid 10001 --gid allsky --home-dir /home/allsky --shell /bin/bash allsky

RUN echo "allsky ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/allsky
RUN chmod 0440 /etc/sudoers.d/allsky


USER allsky

WORKDIR /home/allsky
RUN git clone https://github.com/aaronwmorris/indi-allsky.git


WORKDIR /home/allsky/indi-allsky
RUN ./misc/build_indi_noansible.sh

RUN /home/allsky/indi-allsky/docker_testing/docker_setup.sh

RUN mkdir virtualenv
RUN virtualenv -p $PYTHON_BIN /home/allsky/indi-allsky/virtualenv/indi-allsky

RUN source /home/allsky/indi-allsky/virtualenv/indi-allsky/bin/activate && pip3 install --upgrade pip setuptools wheel
RUN source /home/allsky/indi-allsky/virtualenv/indi-allsky/bin/activate && pip3 install -r requirements_debian11.txt
RUN source /home/allsky/indi-allsky/virtualenv/indi-allsky/bin/activate && pip3 install $PYINDI_VERSION

