### INCOMPLETE ###

FROM indi_allsky

ENV DEBIAN_FRONTEND noninteractive


USER allsky

WORKDIR /home/allsky/indi-allsky

RUN ['/home/allsky/indi-allsky/virtualenv/indi-allsky/bin/gunicorn', '--config', '/etc/indi-allsky/gunicorn.conf.py', 'indi_allsky.wsgi']

